version: "3.9"
services:
  trainers-log-backend:
    container_name: todo_backend
    build:
      dockerfile: Dockerfile
    image: todo-backend:latest
    hostname: todo.backend
    ports:
      - "8080:8080"
    networks:
      - todo-backend-network
    depends_on:
      - postgres

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    hostname: todo.postgres
    volumes:
      - ./db-scripts/init:/docker-entrypoint-initdb.d
    ports:
      - "6432:5432"
    networks:
      - todo-backend-network

networks:
  todo-backend-network:
    driver: bridge